x=msgbox("Can I get a kiss?", 0+32, "can i?")
x=msgbox("And can you make it last forever ?", 0+64, "diz sim")
x=msgbox("I said I'm 'bout to go to war?", 0+48, " tenha cuidado!!")
x=msgbox("And I don't know if I'ma see you again :/", 0+16, " please!")
x=msgbox("Como diria Rubel e quando bate aquela saudade? :(", 0+16, " ???")
x=msgbox("Diz que ja e tarde, que nao tem mais jeito, mas eu nao aceito a decisao do teu coracao em partir.... Reinventar, resplandecer. O que nao apagou, em mim nada mudou, eu sei que o sonho ainda pode acontecer - Belo", 0+16, " Reinventar")
x=msgbox("Entenda, por favor. Que uma carta e muito pouco para revelar o retrato da tristeza e a cicatriz da saudade que voce deixou no meu peito tatuagem de amor, nao tem jeito nunca vai sair de mim essa dor", 0+32, "carta")